[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# replace your chip as listed in `probe-rs chip list`
runner = "probe-rs run --chip STM32WLE5JCIx --chip-description-path STM32WL_Series.yaml"

[build]
target = "thumbv7em-none-eabi"

[env]
DEFMT_LOG = "trace"
